### ISSUE TITLE
Status of DBSCAN Code: Proprietary or Public Domain?

### ISSUE THREAD

**Issue by ensafi** [propanoid/DBSCAN#1]
Hello,

I was wondering if this code is considered proprietary, and therefore not usable in a commercial application, or if it is public domain and can be used for profit, without royalties, either as-is or with modifications and bug fixes?  Does the author need to be acknowledged in any commercial product?

Thank you,

Alex

**Comment by propanoid** [comment]
Hello. I have added a license file. Anyone can use this code as he/she wish, except of Richard Stollman.

**Comment by flying-sheep** [comment]
so it’s not free software and therefore not usable by any project wanting to be free software.

i.e. nothing using a MIT, BSD, Apache, or GPL can use this.

**Comment by propanoid** [comment]
I changed license to 2-clause BSD. Please feel free to use this code. This was not funny joke

**Comment by ensafi** [comment]
Actually, we thought it was hilarious and the best license ever!

But thank you for making it more "standard" if not nearly as creative.
