### ISSUE TITLE
how to use the library with a csv file

### ISSUE THREAD

**Issue by itabhiyanta** [propanoid/DBSCAN#2]
Hi

Can you please suggest how to use the binaries generated with a .csv file and how can i specify number of neighbors i wish to get calculated for each point?

with kind regards
Rohit

**Comment by propanoid** [comment]
Hello
I created a wiki page with basic tool usage instunctions. https://github.com/propanoid/DBSCAN/wiki
Please let me know if you have any difficulties

**Comment by itabhiyanta** [comment]
Hi Vladimir

Thanks for your reply. I wish to find say 63 neighbors for each point in a set of 3D points (stored in a .csv file). What i cannot figure out is (i used the knn_dist binary) how can i do that and which binary should i use.

Is there a binary for k nearest neighbor classification or is the library meant for something else derived from the knn neighbor calculation?
Please don't mind my ignorance.

with kind regards
Rohit

**Comment by propanoid** [comment]
Hi
The knn_dist tool input file format is same as for cluster_csv tool.
For every row of of input knn_dist returns K nearest distance. For example if the -k param is equal to 3, the tool returns 3-rd neighbour distance for every row of input file. 
If you need all neighbours list and their distances you must modify source code. There is no ready tool for this task. 
Please feel free to submit any pull requests
