### ISSUE TITLE
hello，Encounter the defeat

### ISSUE THREAD

**Issue by yangninghua** [propanoid/DBSCAN#3]
dbscan.cpp   
111:
DBSCAN::DistanceMatrix d_m( cl_d.size1(), cl_d.size1() );

Encounter the defeat

VS2015 + win7-X64

**Comment by yangninghua** [comment]
use           test_dbscan.cpp
debug:
DBSCAN::DistanceMatrix d_m( cl_d.size1(), cl_d.size1() );  //cl_d.size1()=100000

**Comment by yangninghua** [comment]
0x000007FEFDEAA06D (located in DBSCANTest1.exe) has an unprocessed exception: Microsoft C++ exception: std:: bad_alloc, located at 0x000000000030F5C0 of memory location.

**Comment by propanoid** [comment]
Hello. Try to use DBSCAN_VP class for 100K points. The distance matrix based DBSCAN is not optimal for such dataset size.
